import { useMemo, useState } from "react";
import { dayOfMonth, monthWeeks, type MonthlyScheduleDiagnostic, type MonthlyScheduleEntry, type MonthlyScheduleTemplate } from "@beosand/types";
import { MonthlyScheduleConflictError } from "../api/client";
import { useGroups } from "../hooks/useGroups";
import { useTrainers } from "../hooks/useTrainers";
import { useCourts } from "../hooks/useCourts";
import { useCreateMonthlySchedulePlan, useMonthlyScheduleActions, useMonthlySchedulePlan } from "../hooks/useMonthlySchedulePlan";
import { Button } from "../ui/Button";
import { Modal } from "../ui/Modal";
import { SelectField } from "../ui/Field";

const MONTHS = ["январь", "февраль", "март", "апрель", "май", "июнь", "июль", "август", "сентябрь", "октябрь", "ноябрь", "декабрь"];
const WEEKDAYS = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"];
const DAYS = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"];
type Action = "approve" | "generate" | "publish" | null;

function diagnosticsFor(entry: MonthlyScheduleEntry, all: MonthlyScheduleDiagnostic[]) {
  return dedupeDiagnostics([...entry.diagnostics, ...all.filter((item) => item.entryId === entry.id)]);
}
function dedupeDiagnostics(items: MonthlyScheduleDiagnostic[]) {
  const seen = new Set<string>();
  return items.filter((item) => {
    const key = `${item.code}|${item.severity}|${item.message}|${item.date}|${item.startTime}|${item.endTime}|${item.entryId ?? ""}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
function court(entry: MonthlyScheduleEntry) { return entry.assignedCourtNumber === null ? "корт не назначен" : `корт ${entry.assignedCourtNumber}`; }

export function SchedulePlanner(): JSX.Element {
  const now = new Date();
  const [year, setYear] = useState(now.getFullYear()); const [month, setMonth] = useState(now.getMonth() + 1);
  const [selectedDate, setSelectedDate] = useState<string | null>(null); const [selectedId, setSelectedId] = useState<string | null>(null);
  const [confirm, setConfirm] = useState<Action>(null); const [conflicts, setConflicts] = useState<MonthlyScheduleDiagnostic[] | null>(null);
  const query = useMonthlySchedulePlan(year, month); const create = useCreateMonthlySchedulePlan(); const actions = useMonthlyScheduleActions();
  const view = query.data ?? null; const plan = view?.plan ?? null;
  const entries = useMemo(() => { const map = new Map<string, MonthlyScheduleEntry[]>(); for (const entry of plan?.entries ?? []) map.set(entry.date, [...(map.get(entry.date) ?? []), entry]); return map; }, [plan]);
  const selected = selectedId ? plan?.entries.find((entry) => entry.id === selectedId) ?? null : null;
  const selectedEntries = selectedDate ? entries.get(selectedDate) ?? [] : [];
  const mutate = async (action: Exclude<Action, null>) => {
    if (!plan) return; setConflicts(null);
    try { if (action === "approve") await actions.approve.mutateAsync(plan.id); if (action === "generate") await actions.generate.mutateAsync(plan.id); if (action === "publish") await actions.publish.mutateAsync(plan.id); setConfirm(null); }
    catch (error) { if (error instanceof MonthlyScheduleConflictError) setConflicts([...error.result.conflicts, ...error.result.warnings]); }
  };
  const busy = create.isPending || actions.approve.isPending || actions.generate.isPending || actions.publish.isPending;
  return <section className="stack schedule-planner">
    <header className="page-head"><div><h1>Планировщик месяца</h1><p>Единый план школы · Европа/Белград · ресурсы и публикация определяет сервер.</p></div>
      {plan ? <div className="planner-head-state"><span className={`tag tag--${plan.status}`}>{plan.status === "draft" ? "Черновик" : plan.status === "approved" ? "Одобрено" : "Опубликовано"}</span><span className="mono">рев. {plan.revision}</span></div> : null}</header>
    <div className="workspace"><div className="workspace__bar planner-bar"><div className="cal-nav"><Button variant="ghost" aria-label="Предыдущий месяц" onClick={() => month === 1 ? (setMonth(12), setYear(year - 1)) : setMonth(month - 1)}>‹</Button><SelectField label="Месяц" value={String(month)} onChange={(e) => setMonth(Number(e.target.value))} options={MONTHS.map((name, index) => ({ value: String(index + 1), label: name }))}/><SelectField label="Год" value={String(year)} onChange={(e) => setYear(Number(e.target.value))} options={Array.from({ length: 7 }, (_, i) => ({ value: String(now.getFullYear() - 2 + i), label: String(now.getFullYear() - 2 + i) }))}/><Button variant="ghost" aria-label="Следующий месяц" onClick={() => month === 12 ? (setMonth(1), setYear(year + 1)) : setMonth(month + 1)}>›</Button></div>
      {view ? <div className="planner-summary mono">{view.summary.templateCount} групп · {view.summary.entryCount} дат · ⚠ {view.summary.blockingDiagnosticCount} · ! {view.summary.warningDiagnosticCount}</div> : null}
      {plan ? <div className="row-actions"><Button variant="ghost" disabled={!view?.actions.canApprove || busy} onClick={() => setConfirm("approve")}>Одобрить план</Button><Button variant="ghost" disabled={!view?.actions.canGenerate || busy} onClick={() => setConfirm("generate")}>Сгенерировать скрытые</Button><Button variant="primary" disabled={!view?.actions.canPublish || busy} onClick={() => setConfirm("publish")}>Опубликовать доступные</Button></div> : null}</div>
      <div className="workspace__body">{query.isPending ? <p className="state">Загружаем план месяца…</p> : query.isError ? <p className="state state--error" role="alert">{query.error.message}</p> : !plan ? <div className="planner-empty"><h2>Плана на {MONTHS[month - 1]} нет</h2><p>Создайте один общий черновик, затем добавьте повторяющиеся расписания групп.</p><Button variant="primary" disabled={create.isPending} onClick={() => create.mutate({ year, month })}>{create.isPending ? "Создаём…" : "Создать план на месяц"}</Button></div> : <><TemplateLedger plan={plan} actions={actions} busy={busy}/><div className="planner-layout"><Calendar year={year} month={month} entries={entries} diagnostics={view!.diagnostics} selectedId={selectedId} onSelect={(entry) => { setSelectedId(entry?.id ?? null); setSelectedDate(entry?.date ?? null); }}/><Inspector date={selectedDate} entries={selectedEntries} selected={selected} diagnostics={conflicts ?? view!.diagnostics}/></div></>}</div></div>
    <ConfirmModal action={confirm} view={view} busy={busy} onClose={() => setConfirm(null)} onConfirm={() => confirm && mutate(confirm)}/>
  </section>;
}

function Calendar({ year, month, entries, diagnostics, selectedId, onSelect }: { year:number; month:number; entries:Map<string, MonthlyScheduleEntry[]>; diagnostics:MonthlyScheduleDiagnostic[]; selectedId:string|null; onSelect:(entry:MonthlyScheduleEntry|null)=>void }) {
  return <div className="planner-calendar" role="grid" aria-label={`План на ${MONTHS[month - 1]} ${year}`}><div className="calendar__head" role="row">{WEEKDAYS.map((day) => <div className="calendar__weekday" role="columnheader" key={day}>{day}</div>)}</div>{monthWeeks(year, month).map((week) => <div className="calendar__week" role="row" key={week.join("|")}>{week.map((date, index) => <div className="calendar__cell" role="gridcell" key={date ?? `blank-${index}`}>{date ? <button type="button" className="planner-day" aria-label={`${date}, занятий: ${(entries.get(date) ?? []).length}`} onClick={() => onSelect((entries.get(date) ?? [])[0] ?? null)}><span className="calendar__date">{dayOfMonth(date)}</span><span className="planner-events">{(entries.get(date) ?? []).slice(0, 3).map((entry) => { const d = diagnosticsFor(entry, diagnostics); return <span key={entry.id} className={selectedId === entry.id ? "planner-occurrence planner-occurrence--selected" : "planner-occurrence"}><b className="mono">{entry.startTime}</b> {entry.groupName}<small>{entry.trainerName} · {court(entry)} {d.length ? `· ⚠ ${d.length}` : ""}</small></span>; })}{(entries.get(date) ?? []).length > 3 ? <span className="planner-more">+ ещё {(entries.get(date) ?? []).length - 3}</span> : null}</span></button> : null}</div>)}</div>)}</div>;
}

function Inspector({ date, entries, selected, diagnostics }: { date:string|null; entries:MonthlyScheduleEntry[]; selected:MonthlyScheduleEntry|null; diagnostics:MonthlyScheduleDiagnostic[] }) {
  const current = selected ?? entries[0] ?? null; const relevant = current ? dedupeDiagnostics([...diagnosticsFor(current, diagnostics), ...diagnostics.filter((item) => item.date === current.date && item.entryId === null)]) : diagnostics.filter((item) => item.date === date);
  return <aside className="workspace__inspector planner-inspector" aria-live="polite"><h2>{date ? `Проверка: ${date}` : "Выберите день"}</h2>{current ? <><div className="planner-facts"><strong>{current.groupName}</strong><span className="mono">{current.startTime}–{current.endTime}</span><span>{current.trainerName} · предпочтение: {current.preferredCourtNumber ? `корт ${current.preferredCourtNumber}` : "нет"}</span><span>Сервер: {court(current)} · {current.hidden ? "скрыта" : "опубликована"}</span></div><h3>Диагностика сервера</h3>{relevant.length ? <ul className="planner-diagnostics">{relevant.map((item, i) => <li className={`planner-diagnostic planner-diagnostic--${item.severity}`} key={`${item.code}-${i}`}><strong>{item.severity === "blocking" ? "Блокирует" : "Предупреждение"}</strong><span className="mono">{item.date} · {item.startTime}–{item.endTime}</span><p>{item.message}</p></li>)}</ul> : <p className="state">Сервер не вернул диагностик для выбранного занятия.</p>}</> : <p className="state">Выберите дату в календаре, чтобы увидеть занятия и причины конфликтов.</p>}</aside>;
}

function TemplateLedger({ plan, actions, busy }: { plan: import("@beosand/types").MonthlySchedulePlan; actions: ReturnType<typeof useMonthlyScheduleActions>; busy:boolean }) {
  const [editing, setEditing] = useState<MonthlyScheduleTemplate | null>(null); const generated = plan.generatedAt !== null;
  return <div className="datatable__surface planner-ledger"><div className="datatable__controlbar"><span>Повторяющиеся расписания групп</span><Button variant="ghost" disabled={generated || busy} onClick={() => setEditing({ id:"", planId:plan.id, groupId:"", groupName:"", levelName:"", daysOfWeek:[1], startTime:"18:00", endTime:"19:30", trainerId:"", trainerName:"", preferredCourtId:null, preferredCourtNumber:null })}>Добавить группу</Button></div><div className="datatable__scroll"><table className="datatable"><thead><tr><th>Группа</th><th>Дни</th><th>Время</th><th>Тренер</th><th>Корт</th><th /></tr></thead><tbody>{plan.templates.map((template) => <tr key={template.id}><td>{template.groupName}</td><td>{template.daysOfWeek.map((day) => DAYS[day - 1]).join(", ")}</td><td className="mono">{template.startTime}–{template.endTime}</td><td>{template.trainerName}</td><td>{template.preferredCourtNumber ? `корт ${template.preferredCourtNumber}` : "без предпочтения"}</td><td><Button variant="ghost" className="btn--sm" onClick={() => setEditing(template)} disabled={busy}>Изменить</Button>{!generated ? <Button variant="ghost" className="btn--sm" onClick={() => actions.deleteTemplate.mutate({ planId:plan.id, templateId:template.id })} disabled={busy}>Удалить</Button> : null}</td></tr>)}</tbody></table></div>{generated ? <p className="planner-ledger-note">После генерации состав групп нельзя менять. Можно изменить только дату, время, тренера или корт; сервер атомарно сохранит изменения либо вернёт все причины.</p> : null}{editing ? <TemplateModal planId={plan.id} template={editing} onClose={() => setEditing(null)} actions={actions}/>:null}</div>;
}

function TemplateModal({ planId, template, onClose, actions }: { planId:string; template:MonthlyScheduleTemplate; onClose:()=>void; actions:ReturnType<typeof useMonthlyScheduleActions> }) { const groups=useGroups(); const trainers=useTrainers(); const courts=useCourts(); const [form,setForm]=useState(template); const save=async()=>{ if(template.id) await actions.updateTemplate.mutateAsync({planId,templateId:template.id,input:{daysOfWeek:form.daysOfWeek,startTime:form.startTime,endTime:form.endTime,trainerId:form.trainerId,preferredCourtId:form.preferredCourtId}}); else await actions.createTemplate.mutateAsync({planId,input:{groupId:form.groupId,daysOfWeek:form.daysOfWeek,startTime:form.startTime,endTime:form.endTime,trainerId:form.trainerId,preferredCourtId:form.preferredCourtId}}); onClose(); }; return <Modal open onClose={onClose} title={template.id ? "Изменить расписание" : "Добавить группу"} footer={<Button variant="primary" onClick={save} disabled={actions.updateTemplate.isPending || actions.createTemplate.isPending}>Сохранить</Button>}><div className="stack"><SelectField label="Группа" disabled={Boolean(template.id)} value={form.groupId} onChange={(e)=>setForm({...form,groupId:e.target.value})} options={[{value:"",label:"Выберите группу"},...(groups.data??[]).map(x=>({value:x.id,label:x.name}))]}/><label>Дни недели <div className="weekday-checks">{DAYS.map((day,index)=><label key={day}><input type="checkbox" checked={form.daysOfWeek.includes(index+1)} onChange={()=>setForm({...form,daysOfWeek:form.daysOfWeek.includes(index+1)?form.daysOfWeek.filter(x=>x!==index+1):[...form.daysOfWeek,index+1]})}/>{day}</label>)}</div></label><label>Время <div className="cluster"><input className="input" type="time" step="1800" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/><input className="input" type="time" step="1800" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></div></label><SelectField label="Тренер" value={form.trainerId} onChange={e=>setForm({...form,trainerId:e.target.value})} options={[{value:"",label:"Выберите тренера"},...(trainers.data??[]).map(x=>({value:x.id,label:x.name}))]}/><SelectField label="Предпочтительный корт" value={form.preferredCourtId??""} onChange={e=>setForm({...form,preferredCourtId:e.target.value||null})} options={[{value:"",label:"Без предпочтения"},...(courts.data??[]).map(x=>({value:x.id,label:`Корт ${x.number}`}))]}/></div></Modal>; }

function ConfirmModal({ action, view, busy, onClose, onConfirm }: { action:Action; view: import("@beosand/types").MonthlySchedulePlanView|null; busy:boolean; onClose:()=>void; onConfirm:()=>void }) { if (!action || !view) return null; const copy = action === "approve" ? "Одобрение фиксирует структуру. Доступность ресурсов будет проверена повторно перед генерацией." : action === "generate" ? `Будет создано ${view.summary.entryCount} скрытых тренировок и связанных блоков кортов. Клиенты их не увидят.` : `Будут опубликованы доступные тренировки; ${view.summary.hiddenTrainingCount} скрытых строк останутся скрытыми.`; return <Modal open onClose={onClose} title={action === "approve" ? "Одобрить план" : action === "generate" ? "Сгенерировать скрытые тренировки" : "Опубликовать доступные тренировки"} footer={<div className="cluster"><Button variant="ghost" onClick={onClose} disabled={busy}>Отмена</Button><Button variant="primary" onClick={onConfirm} disabled={busy}>{busy ? "Выполняем…" : "Подтвердить"}</Button></div>}><p>{copy}</p></Modal>; }
