/* eslint-disable @typescript-eslint/no-explicit-any -- repository run snapshots are JSONB contract payloads. */
import { ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { isAdmin, type Env } from "@beosand/config";
import { ENV } from "../../config/config.module";
import { Inject } from "@nestjs/common";
import { broadcastAutomationListSchema, broadcastAutomationPreviewSchema, broadcastAutomationRunDetailSchema, broadcastAutomationRunListSchema, broadcastAutomationSchema, retryBroadcastAutomationFailuresResultSchema, type BroadcastAutomation, type CreateBroadcastAutomationInput, type EnableBroadcastAutomationInput, type ListBroadcastAutomationRunsQuery, type ListBroadcastAutomationsQuery, type PreviewBroadcastAutomationInput, type RetryBroadcastAutomationFailuresInput, type SetBroadcastAutomationEnabledInput, type UpdateBroadcastAutomationInput } from "@beosand/types";
import { TelegramSender, sanitizeTelegramDiagnostic } from "../notifications/telegram-sender";
import { BroadcastAutomationsRepository, type TrainingRow } from "./broadcast-automations.repository";

const ZONE = "Europe/Belgrade";
const WINDOW_MS = 5 * 60_000;
@Injectable()
export class BroadcastAutomationsService {
  constructor(private readonly repo: BroadcastAutomationsRepository, private readonly sender: TelegramSender, @Inject(ENV) private readonly env: Env) {}
  async list(actor: number, q: ListBroadcastAutomationsQuery) { this.admin(actor); const limit=q.limit ?? 25; const items = await this.repo.list({...q,limit}); return broadcastAutomationListSchema.parse({ items: items.slice(0,limit), nextCursor: items.length > limit ? items[limit].id : null }); }
  async get(actor: number, id: string) { this.admin(actor); return broadcastAutomationSchema.parse(await this.must(id)); }
  async create(actor: number, input: CreateBroadcastAutomationInput) { this.admin(actor); return broadcastAutomationSchema.parse(await this.repo.create(input, actor)); }
  async update(actor: number, id: string, input: UpdateBroadcastAutomationInput) { this.admin(actor); const { expectedVersion, ...patch } = input; const row = await this.repo.update(id, expectedVersion, patch, actor); if (!row) throw new ConflictException("Automation not found or stale version"); return broadcastAutomationSchema.parse(row); }
  async enable(actor: number, id: string, input: EnableBroadcastAutomationInput) { this.admin(actor); const current = await this.must(id); if (current.version !== input.expectedVersion) throw new ConflictException("Stale automation version"); const preview = await this.preview(actor,id,{ expectedVersion: input.expectedVersion }); if (preview.previewToken !== input.previewToken) throw new ConflictException("Stale preview token"); const row = await this.repo.update(id,input.expectedVersion,{},actor,true); if (!row) throw new ConflictException("Automation changed"); return broadcastAutomationSchema.parse(row); }
  async disable(actor: number, id: string, input: SetBroadcastAutomationEnabledInput) { this.admin(actor); const row = await this.repo.update(id,input.expectedVersion,{},actor,false); if (!row) throw new ConflictException("Automation not found or stale version"); return broadcastAutomationSchema.parse(row); }
  async preview(actor: number, id: string, input: PreviewBroadcastAutomationInput) { this.admin(actor); const automation = await this.must(id); if (automation.version !== input.expectedVersion) throw new ConflictException("Stale automation version"); const trainings = automation.trigger.kind === "scheduled" ? await this.repo.qualifyingTrainings(automation.trigger.trainingWindow, belgradeDate(new Date())) : []; const recipients = await this.repo.audience(automation.audience,new Date()); const rendered = this.render(automation, trainings, automation.message.defaultLanguage); const languages = new Set(recipients.map(r=>r.language)); return broadcastAutomationPreviewSchema.parse({ automationId:id,version:automation.version,previewToken:token(automation),trainings,renderedItems:rendered,recipientCount:recipients.length,selectedLanguages:[...languages],fallbackLanguages:[...languages].filter(l=>!automation.message.bodies[l]),warnings: trainings.length ? [] : ["No qualifying trainings at this instant"] }); }
  async listRuns(actor:number,q:ListBroadcastAutomationRunsQuery) { this.admin(actor); const limit=q.limit ??25; const items=await this.repo.listRuns({...q,limit}); return broadcastAutomationRunListSchema.parse({items:items.slice(0,limit),nextCursor:items.length>limit?items[limit].id:null}); }
  async runDetail(actor:number,id:string) { this.admin(actor); const row=await this.repo.detail(id); if(!row) throw new NotFoundException("Automation run not found"); return broadcastAutomationRunDetailSchema.parse(row); }
  async retry(actor:number,runId:string,input:RetryBroadcastAutomationFailuresInput) {
    this.admin(actor);
    const detail=await this.repo.detail(runId);
    if(!detail) throw new NotFoundException("Automation run not found");
    const plan=await this.repo.createRetryRun(detail.run,input.deliveryIds,input.includeAmbiguous ?? false);
    if(!plan) throw new ConflictException("No eligible failed deliveries");
    const automation=await this.must(detail.run.automationId);
    const sourceEventId=await this.rootSourceEventId(detail.run);
    const trainingIds=[...new Set(plan.deliveries.flatMap((delivery)=>delivery.payloadSnapshot.trainingIds))];
    let attempted=0,sent=0,failed=0,ambiguous=0,skipped=0;
    const skip=async (deliveryId:string,reason:"disabled"|"training-ineligible"|"training-no-longer-in-window"|"audience-no-longer-eligible"|"mandatory-exclusion"|"cta-invalid"|"retry-not-eligible")=>{skipped++;await this.repo.skipDelivery(deliveryId,reason);};
    if(!automation.enabled){ for(const delivery of plan.deliveries) await skip(delivery.id,"disabled"); await this.repo.completeRun(plan.run.id,{selectedTrainings:trainingIds.length,includedTrainings:0,recipients:plan.deliveries.length,skippedDeliveries:skipped}); return retryBroadcastAutomationFailuresResultSchema.parse({run:{...plan.run,status:"completed",completedAt:new Date().toISOString(),counts:{...plan.run.counts,selectedTrainings:trainingIds.length,recipients:plan.deliveries.length,skippedDeliveries:skipped}},selectedDeliveryCount:plan.deliveries.length}); }
    const eligible=await this.repo.eligibleTrainings(trainingIds);
    const eligibleIds=new Set(eligible.map((training)=>training.trainingId));
    const scheduled=automation.trigger.kind === "scheduled" ? new Set((await this.repo.qualifyingTrainings(automation.trigger.trainingWindow,belgradeDate(new Date()))).map((training)=>training.trainingId)) : undefined;
    for(const delivery of plan.deliveries){
      const payload=delivery.payloadSnapshot;
      if(payload.ctaMode === "booking" && (payload.trainingIds.length!==1 || !payload.bookingTrainingId || payload.bookingTrainingId!==payload.trainingIds[0])) { await skip(delivery.id,"cta-invalid"); continue; }
      if(payload.ctaMode === "none" && payload.bookingTrainingId!==null) { await skip(delivery.id,"cta-invalid"); continue; }
      if(payload.trainingIds.some((id)=>!eligibleIds.has(id))) { await skip(delivery.id,"training-ineligible"); continue; }
      if(scheduled && payload.trainingIds.some((id)=>!scheduled.has(id))) { await skip(delivery.id,"training-no-longer-in-window"); continue; }
      const recipient=await this.repo.recipientStillEligible(delivery.clientId,automation.audience,new Date());
      if(!recipient) { await skip(delivery.id,"audience-no-longer-eligible"); continue; }
      if(automation.trigger.kind === "freed-place" && await this.repo.hasFreedPlaceExclusion(sourceEventId,delivery.clientId,payload.trainingIds)) { await skip(delivery.id,"mandatory-exclusion"); continue; }
      attempted++;
      const result=await this.sender.sendMessageWithOutcome(recipient.telegramId,payload.text,payload.ctaMode==="booking"?{inline_keyboard:[[{text:"Р—Р°РїРёСЃР°С‚СЊСЃСЏ",callback_data:`book:slot:${payload.bookingTrainingId}`}]]}:undefined);
      if(result.kind==="sent"){sent++;await this.repo.finishDelivery(delivery.id,"sent",null);}else{if(result.kind==="failed")failed++;else ambiguous++;await this.repo.finishDelivery(delivery.id,result.kind,sanitizeTelegramDiagnostic(result.diagnostic));}
    }
    await this.repo.completeRun(plan.run.id,{selectedTrainings:trainingIds.length,includedTrainings:eligible.length,skippedTrainings:trainingIds.length-eligible.length,recipients:plan.deliveries.length,attempted,sent,failed,ambiguous,skippedDeliveries:skipped});
    return retryBroadcastAutomationFailuresResultSchema.parse({run:{...plan.run,status:"completed",completedAt:new Date().toISOString(),counts:{...plan.run.counts,selectedTrainings:trainingIds.length,includedTrainings:eligible.length,skippedTrainings:trainingIds.length-eligible.length,recipients:plan.deliveries.length,attempted,sent,failed,ambiguous,skippedDeliveries:skipped}},selectedDeliveryCount:plan.deliveries.length});
  }

  /** Internal hook for training/bookings services; source ids are the idempotency boundary. */
  async enqueueEvent(trigger: "training-created" | "training-time-changed" | "freed-place", sourceEventId: string): Promise<number> { const automations = await this.repo.list({limit:100,enabled:true}); let count=0; for(const automation of automations) if(automation.trigger.kind===trigger && await this.repo.enqueueEvent(automation,sourceEventId)) count++; return count; }
  async sweep(now = new Date()): Promise<void> { const automations=await this.repo.list({limit:100,enabled:true}); for(const a of automations) if(a.trigger.kind==="scheduled"){ const due=scheduledOccurrence(a,now); if(due) await this.repo.createScheduledRun(a,due); } for(const run of await this.repo.listDue(now)){ if(now.getTime()-new Date(run.dueAt).getTime()>WINDOW_MS){await this.repo.skipRun(run.id,"missed");continue;} const claimed=await this.repo.claimRun(run.id); if(claimed) await this.deliver(claimed,now); } }
  private async deliver(run: any, now:Date):Promise<void>{ const automation=await this.must(run.automationId); if(!automation.enabled){await this.repo.skipRun(run.id,"disabled");return;} const trigger=run.configSnapshot.trigger; const eventTraining=trigger.kind === "scheduled" ? undefined : await this.repo.eventTraining(trigger.kind,run.sourceEventId ?? ""); const trainings=trigger.kind==="scheduled"?await this.repo.qualifyingTrainings(trigger.trainingWindow,belgradeDate(now)):eventTraining?[eventTraining]:[]; if(!trainings.length){await this.repo.skipRun(run.id,"no-qualifying-trainings");return;} const recipients=await this.repo.audience(run.configSnapshot.audience,now); if(!recipients.length){await this.repo.skipRun(run.id,"no-eligible-recipients");return;} const rendered=this.render(automation,trainings,automation.message.defaultLanguage); let attempted=0,sent=0,failed=0,ambiguous=0; for(const item of rendered){const dbItem=await this.repo.createItem(run.id,item.ordinal,automation.message.outputMode,automation.message.ctaMode,item.payload); for(const tr of trainings) await this.repo.addTraining(run.id,dbItem.id,tr.trainingId,tr,run.sourceEventId ?? undefined); for(const recipient of recipients){const payload=this.render(automation,trainings,recipient.language)[Math.min(item.ordinal-1,rendered.length-1)].payload; const delivery=await this.repo.claimDelivery(run.id,dbItem.id,recipient,payload); if(!delivery)continue; attempted++; const result=await this.sender.sendMessageWithOutcome(recipient.telegramId,payload.text,payload.ctaMode==="booking"?{inline_keyboard:[[{text:"Записаться",callback_data:`book:slot:${payload.bookingTrainingId}`}]]}:undefined); if(result.kind==="sent"){sent++;await this.repo.finishDelivery(delivery.id,"sent",null);}else{if(result.kind==="failed")failed++;else ambiguous++;await this.repo.finishDelivery(delivery.id,result.kind,sanitizeTelegramDiagnostic(result.diagnostic));}}} await this.repo.completeRun(run.id,{selectedTrainings:trainings.length,includedTrainings:trainings.length,recipients:recipients.length,attempted,sent,failed,ambiguous}); }
  private render(automation:BroadcastAutomation,trainings:TrainingRow[], language:"ru"|"sr"|"en"){ const resolved=automation.message.bodies[language]?language:automation.message.defaultLanguage; const make=(set:TrainingRow[],ordinal:number)=>({ordinal,payload:{trainingIds:set.map(t=>t.trainingId),requestedLanguage:language,resolvedLanguage:resolved,usedFallback:resolved!==language,text:renderBody(automation.message.bodies[resolved] ?? "",set),ctaMode:automation.message.ctaMode,bookingTrainingId:automation.message.ctaMode==="booking"?set[0]?.trainingId ?? null:null}}); return automation.message.outputMode==="digest"?(trainings.length?[make(trainings,1)]:[]):trainings.map((t,i)=>make([t],i+1)); }
  private async must(id:string){const row=await this.repo.find(id);if(!row)throw new NotFoundException("Automation not found");return row;}
  private async rootSourceEventId(run: { sourceEventId: string | null; originalRunId: string | null }): Promise<string | null> { let current=run; while(!current.sourceEventId && current.originalRunId){const detail=await this.repo.detail(current.originalRunId);if(!detail)break;current=detail.run;} return current.sourceEventId; }
  private admin(id:number){if(!isAdmin(this.env,id))throw new ForbiddenException("Admin privileges required");}
}
function renderBody(body:string, trainings:TrainingRow[]):string{return body.replace(/\{\{\s*(groupName|date|startTime|endTime|freeSeats)\s*\}\}/g,(_,k)=>String(trainings[0]?.[k as keyof TrainingRow] ?? "")).replace(/\{\{\s*trainings\s*\}\}/g,trainings.map(t=>`${t.groupName} — ${t.date} ${t.startTime}`).join("\n"));}
function token(a:BroadcastAutomation){return Buffer.from(`${a.id}:${a.version}:${a.updatedAt}`).toString("base64url");}
function belgradeDate(now:Date){return new Intl.DateTimeFormat("en-CA",{timeZone:ZONE,year:"numeric",month:"2-digit",day:"2-digit"}).format(now);}
function scheduledOccurrence(a:BroadcastAutomation,now:Date):Date|undefined{const t=a.trigger;if(t.kind!=="scheduled")return;const p=new Intl.DateTimeFormat("en-GB",{timeZone:ZONE,weekday:"short",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(now);const x=Object.fromEntries(p.map(q=>[q.type,q.value]));const date=`${x.year}-${x.month}-${x.day}`, minute=`${x.hour}:${x.minute}`;if(minute!==t.time)return;if(t.recurrence==="one-time"&&t.date!==date)return;if(t.recurrence==="weekly"&&!t.weekdays?.includes(({Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7} as Record<string,number>)[x.weekday]))return;return now;}
