/* eslint-disable @typescript-eslint/no-explicit-any -- repository run snapshots are JSONB contract payloads. */
import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { isAdmin, type Env } from "@beosand/config";
import { ENV } from "../../config/config.module";
import { Inject } from "@nestjs/common";
import { broadcastAutomationListSchema, broadcastAutomationPreviewSchema, broadcastAutomationRunDetailSchema, broadcastAutomationRunListSchema, broadcastAutomationSchema, retryBroadcastAutomationFailuresResultSchema, type BroadcastAutomation, type CreateBroadcastAutomationInput, type EnableBroadcastAutomationInput, type ListBroadcastAutomationRunsQuery, type ListBroadcastAutomationsQuery, type PreviewBroadcastAutomationInput, type RetryBroadcastAutomationFailuresInput, type SetBroadcastAutomationEnabledInput, type UpdateBroadcastAutomationInput } from "@beosand/types";
import { TelegramSender, sanitizeTelegramDiagnostic } from "../notifications/telegram-sender";
import { bookSlotsKeyboard } from "../notifications/notification-keyboards";
import { BroadcastAutomationsRepository, type TrainingRow } from "./broadcast-automations.repository";
import { normalizeAutomationConfig } from "./broadcast-automation-config";

const ZONE = "Europe/Belgrade";
const WINDOW_MS = 5 * 60_000;
const SCHEDULE_GRACE_MS = 60_000;
const PROCESSING_LEASE_MS = 10 * 60_000;
const AUTOMATION_PAGE_SIZE = 100;
@Injectable()
export class BroadcastAutomationsService {
  constructor(private readonly repo: BroadcastAutomationsRepository, private readonly sender: TelegramSender, @Inject(ENV) private readonly env: Env) {}
  async list(actor: number, q: ListBroadcastAutomationsQuery) { this.admin(actor); const limit=q.limit ?? 25; const items = await this.repo.list({...q,limit}); return broadcastAutomationListSchema.parse({ items: items.slice(0,limit), nextCursor: items.length > limit ? items[limit - 1].id : null }); }
  async get(actor: number, id: string) { this.admin(actor); return broadcastAutomationSchema.parse(await this.must(id)); }
  async create(actor: number, input: CreateBroadcastAutomationInput) { this.admin(actor); this.validateSchedule(input.trigger); return broadcastAutomationSchema.parse(await this.repo.create(input, actor)); }
  async update(actor: number, id: string, input: UpdateBroadcastAutomationInput) { this.admin(actor); const current = await this.must(id); if (current.version !== input.expectedVersion) throw new ConflictException("Automation not found or stale version"); const { expectedVersion, ...patch } = input; this.validateSchedule(patch.trigger ?? current.trigger); const row = await this.repo.update(id, expectedVersion, patch, actor); if (!row) throw new ConflictException("Automation not found or stale version"); return broadcastAutomationSchema.parse(row); }
  async enable(actor: number, id: string, input: EnableBroadcastAutomationInput) { this.admin(actor); const current = await this.must(id); if (current.version !== input.expectedVersion) throw new ConflictException("Stale automation version"); const oneTimeAt=current.trigger.kind==="scheduled"&&current.trigger.recurrence==="one-time"&&current.trigger.date?localInstant(current.trigger.date,current.trigger.time):undefined; if(current.trigger.kind==="scheduled"&&current.trigger.recurrence==="one-time"&&(!oneTimeAt||oneTimeAt.getTime()<=Date.now())) throw new ConflictException("One-time schedule is in the past"); const preview = await this.preview(actor,id,{ expectedVersion: input.expectedVersion }); if (preview.previewToken !== input.previewToken) throw new ConflictException("Stale preview token"); const row = await this.repo.update(id,input.expectedVersion,{},actor,true); if (!row) throw new ConflictException("Automation changed"); return broadcastAutomationSchema.parse(row); }
  async disable(actor: number, id: string, input: SetBroadcastAutomationEnabledInput) { this.admin(actor); const row = await this.repo.update(id,input.expectedVersion,{},actor,false); if (!row) throw new ConflictException("Automation not found or stale version"); return broadcastAutomationSchema.parse(row); }
  async preview(actor: number, id: string, input: PreviewBroadcastAutomationInput) { this.admin(actor); const automation = await this.must(id); if (automation.version !== input.expectedVersion) throw new ConflictException("Stale automation version"); const trainings = automation.trigger.kind === "scheduled" ? await this.repo.qualifyingTrainings(automation.trigger.trainingWindow, belgradeDate(new Date())) : []; const recipients = await this.repo.audience(automation.audience,new Date()); const rendered = this.render(automation, trainings, automation.message.defaultLanguage); const languages = new Set(recipients.map(r=>r.language)); return broadcastAutomationPreviewSchema.parse({ automationId:id,version:automation.version,previewToken:token(automation),trainings,renderedItems:rendered,recipientCount:recipients.length,selectedLanguages:[...languages],fallbackLanguages:[...languages].filter(l=>!automation.message.bodies[l]),warnings: trainings.length ? [] : ["No qualifying trainings at this instant"] }); }
  async listRuns(actor:number,q:ListBroadcastAutomationRunsQuery) { this.admin(actor); const limit=q.limit ??25; const items=await this.repo.listRuns({...q,limit}); return broadcastAutomationRunListSchema.parse({items:items.slice(0,limit),nextCursor:items.length>limit?items[limit-1].id:null}); }
  async runDetail(actor:number,id:string) { this.admin(actor); const row=await this.repo.detail(id); if(!row) throw new NotFoundException("Automation run not found"); return broadcastAutomationRunDetailSchema.parse(row); }
  async retry(actor:number,runId:string,input:RetryBroadcastAutomationFailuresInput) {
    this.admin(actor); const detail=await this.repo.detail(runId); if(!detail) throw new NotFoundException("Automation run not found"); let plan=await this.repo.createRetryRun(detail.run,input.deliveryIds,input.includeAmbiguous ?? false); if(!plan) throw new ConflictException("No eligible failed deliveries"); plan={...plan,run:{...plan.run,configSnapshot:normalizeAutomationConfig(plan.run.configSnapshot)}};
    const automation=await this.must(detail.run.automationId), config=plan.run.configSnapshot, sourceEventId=await this.rootSourceEventId(detail.run), trainingIds=[...new Set(plan.deliveries.flatMap((d)=>d.payloadSnapshot.trainingIds))]; let attempted=0,sent=0,failed=0,ambiguous=0,skipped=0;
    const skip=async (id:string,reason:"disabled"|"training-ineligible"|"training-no-longer-in-window"|"audience-no-longer-eligible"|"mandatory-exclusion"|"cta-invalid"|"retry-not-eligible")=>{skipped++;await this.repo.skipDelivery(id,reason);};
    if(!automation.enabled){ for(const d of plan.deliveries) await skip(d.id,"disabled"); await this.repo.completeRun(plan.run.id,{selectedTrainings:trainingIds.length,recipients:plan.deliveries.length,skippedDeliveries:skipped}); return retryBroadcastAutomationFailuresResultSchema.parse({run:{...plan.run,status:"completed",completedAt:new Date().toISOString(),counts:{...plan.run.counts,selectedTrainings:trainingIds.length,recipients:plan.deliveries.length,skippedDeliveries:skipped}},selectedDeliveryCount:plan.deliveries.length}); }
    const eligible=await this.repo.eligibleTrainings(trainingIds), eligibleIds=new Set(eligible.map((t)=>t.trainingId)), scheduled=config.trigger.kind === "scheduled" ? new Set((await this.repo.qualifyingTrainings(config.trigger.trainingWindow,belgradeDate(new Date()))).map((t)=>t.trainingId)) : undefined;
    for(const d of plan.deliveries){ const payload=d.payloadSnapshot; if((payload.ctaMode==="booking"&&(payload.trainingIds.length!==1||!payload.bookingTrainingId||payload.bookingTrainingId!==payload.trainingIds[0]))||(payload.ctaMode==="none"&&payload.bookingTrainingId!==null)){await skip(d.id,"cta-invalid");continue;} if(payload.trainingIds.some((id)=>!eligibleIds.has(id))){await skip(d.id,"training-ineligible");continue;} if(scheduled&&payload.trainingIds.some((id)=>!scheduled.has(id))){await skip(d.id,"training-no-longer-in-window");continue;} const recipient=await this.repo.recipientStillEligible(d.clientId,config.audience,new Date()); if(!recipient){await skip(d.id,"audience-no-longer-eligible");continue;} if(config.trigger.kind==="freed-place"&&await this.repo.hasFreedPlaceExclusion(sourceEventId,d.clientId,payload.trainingIds)){await skip(d.id,"mandatory-exclusion");continue;} attempted++; const result=await this.sender.sendMessageWithOutcome(recipient.telegramId,payload.text,keyboard(payload,eligible.find((training)=>training.trainingId===payload.bookingTrainingId))); if(result.kind==="sent"){sent++;await this.repo.finishDelivery(d.id,"sent",null);}else{if(result.kind==="failed")failed++;else ambiguous++;await this.repo.finishDelivery(d.id,result.kind,sanitizeTelegramDiagnostic(result.diagnostic));} }
    await this.repo.completeRun(plan.run.id,{selectedTrainings:trainingIds.length,includedTrainings:eligible.length,skippedTrainings:trainingIds.length-eligible.length,recipients:plan.deliveries.length,attempted,sent,failed,ambiguous,skippedDeliveries:skipped}); return retryBroadcastAutomationFailuresResultSchema.parse({run:{...plan.run,status:"completed",completedAt:new Date().toISOString(),counts:{...plan.run.counts,selectedTrainings:trainingIds.length,includedTrainings:eligible.length,skippedTrainings:trainingIds.length-eligible.length,recipients:plan.deliveries.length,attempted,sent,failed,ambiguous,skippedDeliveries:skipped}},selectedDeliveryCount:plan.deliveries.length});
  }
  async enqueueEvent(trigger: "training-created" | "training-time-changed" | "freed-place", sourceEventId: string): Promise<number> { let count=0; for(const automation of await this.enabledAutomations()) if(automation.trigger.kind===trigger && await this.repo.enqueueEvent(automation,sourceEventId)) count++; return count; }
  async sweep(now = new Date()): Promise<void> { await this.repo.recoverExpiredProcessing?.(now,new Date(now.getTime()-PROCESSING_LEASE_MS)); for(const automation of await this.enabledAutomations()) if(automation.trigger.kind==="scheduled"){ const cursor=await this.repo.schedulerCursor?.(automation.id); for(const occurrence of scheduledOccurrences(automation,cursor ?? belgradeDayStart(now),now)) await this.repo.createScheduledRun(automation,occurrence.scheduledFor,occurrence.skip ? "skipped" : now.getTime()-occurrence.scheduledFor.getTime()>=SCHEDULE_GRACE_MS?"skipped":"pending"); await this.repo.recordSchedulerCursor?.(automation.id,now); } for(const run of await this.repo.listDue(now)){ if(now.getTime()-new Date(run.dueAt).getTime()>WINDOW_MS){await this.repo.skipRun(run.id,"missed");continue;} const claimed=await this.repo.claimRun(run.id); if(claimed) await this.deliver(claimed,now); } }
  private async deliver(run:any,now:Date):Promise<void>{
    const automation=await this.must(run.automationId);
    if(!automation.enabled){await this.repo.skipRun(run.id,"disabled");return;}
    const config=run.configSnapshot, trigger=config.trigger, eventResolution=trigger.kind==="scheduled"?undefined:await this.repo.eventTraining(trigger.kind,run.sourceEventId ?? ""), legacyEventTraining=legacyTraining(eventResolution)?eventResolution:undefined, eventTraining=legacyEventTraining ?? eventResolution?.training, trainings=trigger.kind==="scheduled"?await this.repo.qualifyingTrainings(trigger.trainingWindow,belgradeDate(now)):eventTraining?[eventTraining]:[];
    const eventSkip = trigger.kind === "scheduled" ? undefined : legacyEventTraining ? legacyEventTraining.freeSeats <= 0 ? { snapshot: legacyEventTraining, skipReason: "training-full" as const } : undefined : eventResolution?.skipReason ? { snapshot: eventResolution.snapshot, skipReason: eventResolution.skipReason } : undefined;
    if(eventSkip){
      if(eventSkip.snapshot){ const evidence=this.render(config,[eventSkip.snapshot],config.message.defaultLanguage)[0]; const item=await this.repo.createItem(run.id,evidence.ordinal,config.message.outputMode,config.message.ctaMode,evidence.payload); await this.repo.addTraining(run.id,item.id,eventSkip.snapshot.trainingId,eventSkip.snapshot,run.sourceEventId ?? undefined,"skipped",eventSkip.skipReason); await this.repo.completeRun(run.id,{selectedTrainings:1,skippedTrainings:1},eventSkip.skipReason); }
      else await this.repo.skipRun(run.id,eventSkip.skipReason);
      return;
    }
    if(!trainings.length){await this.repo.skipRun(run.id,"no-qualifying-trainings");return;}
    const recipients=await this.repo.audience(config.audience,now);
    if(!recipients.length){await this.repo.skipRun(run.id,"no-eligible-recipients");return;}
    const covered=trigger.kind==="scheduled"&&config.message.outputMode==="digest"?await this.repo.eventCoveredTrainingIdsSince(run.automationId,new Date(run.scheduledFor ?? now),new Date(automation.createdAt),trainings.map((training:TrainingRow)=>training.trainingId)):new Map<string,string>();
    const included=trainings.filter((training:TrainingRow)=>!covered.has(training.trainingId));
    const rendered=this.render(config,included,config.message.defaultLanguage);
    let attempted=0,sent=0,failed=0,ambiguous=0,skippedDeliveries=0;
    const sendItem=async(dbItemId:string,ordinal:number,itemTrainings:TrainingRow[])=>{
      for(const recipient of recipients){
        const payload=this.render(config,itemTrainings,recipient.language)[Math.min(ordinal-1,this.render(config,itemTrainings,recipient.language).length-1)].payload;
        const delivery=await this.repo.claimDelivery(run.id,dbItemId,recipient,payload);
        if(!delivery)continue;
        const currentRecipient=await this.repo.recipientStillEligible(recipient.clientId,config.audience,new Date());
        if(!currentRecipient){skippedDeliveries++;await this.repo.skipDelivery(delivery.id,"audience-no-longer-eligible");continue;}
        if(trigger.kind==="freed-place"&&await this.repo.hasFreedPlaceExclusion(run.sourceEventId,currentRecipient.clientId,payload.trainingIds)){skippedDeliveries++;await this.repo.skipDelivery(delivery.id,"mandatory-exclusion");continue;}
        attempted++;
        const result=await this.sender.sendMessageWithOutcome(currentRecipient.telegramId,payload.text,keyboard(payload,itemTrainings.find((training)=>training.trainingId===payload.bookingTrainingId)));
        if(result.kind==="sent"){sent++;await this.repo.finishDelivery(delivery.id,"sent",null);}else{if(result.kind==="failed")failed++;else ambiguous++;await this.repo.finishDelivery(delivery.id,result.kind,sanitizeTelegramDiagnostic(result.diagnostic,currentRecipient.telegramId));}
      }
    };
    if(trigger.kind==="scheduled"&&config.message.outputMode==="digest"&&covered.size){
      const evidence=this.render(config,included.length?included:trainings,config.message.defaultLanguage)[0];
      const dbItem=await this.repo.createItem(run.id,evidence.ordinal,config.message.outputMode,config.message.ctaMode,evidence.payload);
      for(const training of included)await this.repo.addTraining(run.id,dbItem.id,training.trainingId,training);
      for(const training of trainings.filter((candidate:TrainingRow)=>covered.has(candidate.trainingId)))await this.repo.addTraining(run.id,dbItem.id,training.trainingId,training,covered instanceof Map ? covered.get(training.trainingId) : undefined,"skipped","training-covered-by-event");
      if(included.length)await sendItem(dbItem.id,evidence.ordinal,included);
    }else for(const item of rendered){
      const itemTrainings=included.filter((training:TrainingRow)=>item.payload.trainingIds.includes(training.trainingId));
      const dbItem=await this.repo.createItem(run.id,item.ordinal,config.message.outputMode,config.message.ctaMode,item.payload);
      for(const training of itemTrainings)await this.repo.addTraining(run.id,dbItem.id,training.trainingId,training,run.sourceEventId ?? undefined);
      await sendItem(dbItem.id,item.ordinal,itemTrainings);
    }
    await this.repo.completeRun(run.id,{selectedTrainings:trainings.length,includedTrainings:included.length,skippedTrainings:covered.size,recipients:recipients.length,attempted,sent,failed,ambiguous,skippedDeliveries});
  }
  private render(automation:Pick<BroadcastAutomation,"name"|"trigger"|"audience"|"message">,trainings:TrainingRow[],language:"ru"|"sr"|"en"){const resolved=automation.message.bodies[language]?language:automation.message.defaultLanguage;const make=(set:TrainingRow[],ordinal:number)=>({ordinal,payload:{trainingIds:set.map(t=>t.trainingId),requestedLanguage:language,resolvedLanguage:resolved,usedFallback:resolved!==language,text:renderBody(automation.message.bodies[resolved] ?? "",set),ctaMode:automation.message.ctaMode,bookingTrainingId:automation.message.ctaMode==="booking"?set[0]?.trainingId ?? null:null}});return automation.message.outputMode==="digest"?(trainings.length?[make(trainings,1)]:[]):trainings.map((t,i)=>make([t],i+1));}
  private async must(id:string){const row=await this.repo.find(id);if(!row)throw new NotFoundException("Automation not found");return row;}
  private async rootSourceEventId(run:{sourceEventId:string|null;originalRunId:string|null}):Promise<string|null>{let current=run;while(!current.sourceEventId&&current.originalRunId){const detail=await this.repo.detail(current.originalRunId);if(!detail)break;current=detail.run;}return current.sourceEventId;}
  private async enabledAutomations(): Promise<BroadcastAutomation[]> { const automations: BroadcastAutomation[]=[]; let cursor: string | undefined; do { const page=await this.repo.list({limit:AUTOMATION_PAGE_SIZE + 1,enabled:true,cursor}); automations.push(...page.slice(0,AUTOMATION_PAGE_SIZE)); cursor=page.length>AUTOMATION_PAGE_SIZE?page[AUTOMATION_PAGE_SIZE-1].id:undefined; } while(cursor); return automations; }
  private validateSchedule(trigger: BroadcastAutomation["trigger"]): void { if(trigger.kind!=="scheduled")return; if(!realDate(trigger.date ?? belgradeDate(new Date())))throw new BadRequestException("Schedule date must be a real calendar date"); if(trigger.recurrence==="one-time"){ const instant=trigger.date ? localInstant(trigger.date,trigger.time) : undefined; if(!instant)throw new BadRequestException("One-time schedule is not a valid Europe/Belgrade instant"); if(instant.getTime()<=Date.now())throw new BadRequestException("One-time schedule must be in the future"); } }
  private admin(id:number){if(!isAdmin(this.env,id))throw new ForbiddenException("Admin privileges required");}
}
function keyboard(payload:{ctaMode:"none"|"booking";bookingTrainingId:string|null;resolvedLanguage:"ru"|"sr"|"en"},training:TrainingRow|undefined){return payload.ctaMode==="booking"&&training?bookSlotsKeyboard(payload.resolvedLanguage,[{trainingId:training.trainingId,startTime:training.startTime,levelName:training.levelName,groupName:training.groupName}]):undefined;}
function legacyTraining(value: unknown): value is TrainingRow { return typeof value === "object" && value !== null && "trainingId" in value && "freeSeats" in value; }
function renderBody(body:string,trainings:TrainingRow[]):string{const training=trainings[0];const values:Record<string,string>={freeSeats:String(training?.freeSeats ?? ""),date:training?.date ?? "",startTime:training?.startTime ?? "",endTime:training?.endTime ?? "",trainer:training?.trainerName ?? "",level:training?.levelName ?? "",price:training?`${training.priceSingleRsd} RSD`:"",groupName:training?.groupName ?? ""};return body.replace(/\{(freeSeats|date|startTime|endTime|trainer|level|price|groupName)\}/g,(_,key)=>values[key] ?? "");}
function token(a:BroadcastAutomation){return Buffer.from(`${a.id}:${a.version}:${a.updatedAt}`).toString("base64url");}
function belgradeDate(now:Date){return localParts(now).date;}
function belgradeDayStart(now:Date){const {date}=localParts(now);return localInstant(date,"00:00") ?? now;}
function scheduledOccurrences(a:BroadcastAutomation,from:Date,to:Date):{scheduledFor:Date;skip:boolean}[]{const trigger=a.trigger;if(trigger.kind!=="scheduled"||from>=to)return[];const dates=datesBetween(localParts(from).date,localParts(to).date);return dates.filter(date=>matchesSchedule(trigger,date)).map(date=>{const exact=localInstant(date,trigger.time);return exact?{scheduledFor:exact,skip:false}:{scheduledFor:firstInstantAfterLocalTime(date,trigger.time),skip:true};}).filter((occurrence):occurrence is {scheduledFor:Date;skip:boolean}=>occurrence.scheduledFor!==undefined).filter(occurrence=>occurrence.scheduledFor.getTime()>from.getTime()&&occurrence.scheduledFor.getTime()<=to.getTime());}
function matchesSchedule(trigger:Extract<BroadcastAutomation["trigger"],{kind:"scheduled"}>,date:string){if(trigger.recurrence==="one-time")return trigger.date===date;if(trigger.recurrence==="daily")return true;return trigger.weekdays?.includes(weekday(date)) ?? false;}
function localParts(now:Date){const values=Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone:ZONE,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(now).filter(p=>p.type!=="literal").map(p=>[p.type,p.value]));return {date:`${values.year}-${values.month}-${values.day}`,time:`${values.hour}:${values.minute}`};}
/** The first matching UTC minute is the canonical identity for a repeated DST local time. */
function localInstant(date:string,time:string):Date|undefined{const guess=Date.parse(`${date}T${time}:00.000Z`);for(let offset=14*60;offset>=-14*60;offset--){const candidate=new Date(guess-offset*60_000);const p=localParts(candidate);if(p.date===date&&p.time===time)return candidate;}return undefined;}
/** Spring-forward gaps have no wall-clock instant; audit them at the first valid local minute after the requested time. */
function firstInstantAfterLocalTime(date:string,time:string):Date|undefined{for(let minute=0;minute<=180;minute++){const candidate=localInstant(date,addMinutes(time,minute));if(candidate)return candidate;}return undefined;}
function addMinutes(time:string,minutes:number):string{const [hour,minute]=time.split(":").map(Number);const total=hour*60+minute+minutes;return `${String(Math.floor(total/60)%24).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`;}
function datesBetween(start:string,end:string){const dates:string[]=[];for(let day=new Date(`${start}T00:00:00.000Z`);day<=new Date(`${end}T00:00:00.000Z`);day.setUTCDate(day.getUTCDate()+1))dates.push(day.toISOString().slice(0,10));return dates;}
function weekday(date:string){return ((new Date(`${date}T00:00:00.000Z`).getUTCDay()+6)%7)+1;}
function realDate(date:string):boolean{const parsed=new Date(`${date}T00:00:00.000Z`);return !Number.isNaN(parsed.getTime())&&parsed.toISOString().slice(0,10)===date;}
