ALTER TABLE "monthly_schedule_plans" ADD COLUMN "start_date" date;
ALTER TABLE "monthly_schedule_plans" ADD COLUMN "end_date" date;
UPDATE "monthly_schedule_plans" SET "start_date" = make_date("year", "month", 1), "end_date" = (make_date("year", "month", 1) + interval '1 month - 1 day')::date;
ALTER TABLE "monthly_schedule_plans" ALTER COLUMN "start_date" SET NOT NULL;
ALTER TABLE "monthly_schedule_plans" ALTER COLUMN "end_date" SET NOT NULL;
ALTER TABLE "monthly_schedule_plans" ADD CONSTRAINT "monthly_schedule_plans_period_order" CHECK ("end_date" >= "start_date");
ALTER TABLE "monthly_schedule_plans" ADD CONSTRAINT "monthly_schedule_plans_period_length" CHECK ("end_date" - "start_date" + 1 BETWEEN 1 AND 84);
CREATE UNIQUE INDEX "monthly_schedule_plans_start_end_idx" ON "monthly_schedule_plans" ("start_date", "end_date");
CREATE INDEX "monthly_schedule_plans_range_idx" ON "monthly_schedule_plans" USING gist (daterange("start_date", "end_date", '[]'));
ALTER TABLE "monthly_schedule_notification_deliveries" ADD COLUMN "period_start" date;
ALTER TABLE "monthly_schedule_notification_deliveries" ADD COLUMN "period_end" date;
UPDATE "monthly_schedule_notification_deliveries" AS delivery SET "period_start" = plan."start_date", "period_end" = plan."end_date" FROM "monthly_schedule_plans" AS plan WHERE plan."id" = delivery."plan_id";
ALTER TABLE "monthly_schedule_notification_deliveries" ALTER COLUMN "period_start" SET NOT NULL;
ALTER TABLE "monthly_schedule_notification_deliveries" ALTER COLUMN "period_end" SET NOT NULL;
ALTER TABLE "monthly_schedule_notification_deliveries" ADD CONSTRAINT "monthly_schedule_notification_deliveries_period_order" CHECK ("period_end" >= "period_start");
CREATE TABLE "monthly_schedule_plan_days_off" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "plan_id" uuid NOT NULL REFERENCES "monthly_schedule_plans"("id") ON DELETE cascade, "date" date NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX "monthly_schedule_plan_days_off_plan_date_idx" ON "monthly_schedule_plan_days_off" ("plan_id", "date");
DROP INDEX "monthly_schedule_plans_year_month_idx";
ALTER TABLE "monthly_schedule_plans" DROP COLUMN "year";
ALTER TABLE "monthly_schedule_plans" DROP COLUMN "month";
ALTER TABLE "monthly_schedule_notification_deliveries" DROP COLUMN "year";
ALTER TABLE "monthly_schedule_notification_deliveries" DROP COLUMN "month";